---
name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    name: release
    runs-on: ubuntu-lates
    steps:
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
